// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SergeyBogomolovv/fitflow/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AdminRepo is an autogenerated mock type for the AdminRepo type
type AdminRepo struct {
	mock.Mock
}

type AdminRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminRepo) EXPECT() *AdminRepo_Expecter {
	return &AdminRepo_Expecter{mock: &_m.Mock}
}

// AdminByLogin provides a mock function with given fields: ctx, login
func (_m *AdminRepo) AdminByLogin(ctx context.Context, login string) (domain.Admin, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for AdminByLogin")
	}

	var r0 domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Admin, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Admin); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(domain.Admin)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepo_AdminByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminByLogin'
type AdminRepo_AdminByLogin_Call struct {
	*mock.Call
}

// AdminByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *AdminRepo_Expecter) AdminByLogin(ctx interface{}, login interface{}) *AdminRepo_AdminByLogin_Call {
	return &AdminRepo_AdminByLogin_Call{Call: _e.mock.On("AdminByLogin", ctx, login)}
}

func (_c *AdminRepo_AdminByLogin_Call) Run(run func(ctx context.Context, login string)) *AdminRepo_AdminByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AdminRepo_AdminByLogin_Call) Return(_a0 domain.Admin, _a1 error) *AdminRepo_AdminByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepo_AdminByLogin_Call) RunAndReturn(run func(context.Context, string) (domain.Admin, error)) *AdminRepo_AdminByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// AdminExists provides a mock function with given fields: ctx, login
func (_m *AdminRepo) AdminExists(ctx context.Context, login string) (bool, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for AdminExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepo_AdminExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminExists'
type AdminRepo_AdminExists_Call struct {
	*mock.Call
}

// AdminExists is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *AdminRepo_Expecter) AdminExists(ctx interface{}, login interface{}) *AdminRepo_AdminExists_Call {
	return &AdminRepo_AdminExists_Call{Call: _e.mock.On("AdminExists", ctx, login)}
}

func (_c *AdminRepo_AdminExists_Call) Run(run func(ctx context.Context, login string)) *AdminRepo_AdminExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AdminRepo_AdminExists_Call) Return(_a0 bool, _a1 error) *AdminRepo_AdminExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepo_AdminExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *AdminRepo_AdminExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAdmin provides a mock function with given fields: ctx, login
func (_m *AdminRepo) DeleteAdmin(ctx context.Context, login string) error {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminRepo_DeleteAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAdmin'
type AdminRepo_DeleteAdmin_Call struct {
	*mock.Call
}

// DeleteAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *AdminRepo_Expecter) DeleteAdmin(ctx interface{}, login interface{}) *AdminRepo_DeleteAdmin_Call {
	return &AdminRepo_DeleteAdmin_Call{Call: _e.mock.On("DeleteAdmin", ctx, login)}
}

func (_c *AdminRepo_DeleteAdmin_Call) Run(run func(ctx context.Context, login string)) *AdminRepo_DeleteAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AdminRepo_DeleteAdmin_Call) Return(_a0 error) *AdminRepo_DeleteAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminRepo_DeleteAdmin_Call) RunAndReturn(run func(context.Context, string) error) *AdminRepo_DeleteAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAdmin provides a mock function with given fields: ctx, login, password
func (_m *AdminRepo) SaveAdmin(ctx context.Context, login string, password []byte) error {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for SaveAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminRepo_SaveAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAdmin'
type AdminRepo_SaveAdmin_Call struct {
	*mock.Call
}

// SaveAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password []byte
func (_e *AdminRepo_Expecter) SaveAdmin(ctx interface{}, login interface{}, password interface{}) *AdminRepo_SaveAdmin_Call {
	return &AdminRepo_SaveAdmin_Call{Call: _e.mock.On("SaveAdmin", ctx, login, password)}
}

func (_c *AdminRepo_SaveAdmin_Call) Run(run func(ctx context.Context, login string, password []byte)) *AdminRepo_SaveAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *AdminRepo_SaveAdmin_Call) Return(_a0 error) *AdminRepo_SaveAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminRepo_SaveAdmin_Call) RunAndReturn(run func(context.Context, string, []byte) error) *AdminRepo_SaveAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, login, password
func (_m *AdminRepo) UpdatePassword(ctx context.Context, login string, password []byte) error {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminRepo_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type AdminRepo_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password []byte
func (_e *AdminRepo_Expecter) UpdatePassword(ctx interface{}, login interface{}, password interface{}) *AdminRepo_UpdatePassword_Call {
	return &AdminRepo_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, login, password)}
}

func (_c *AdminRepo_UpdatePassword_Call) Run(run func(ctx context.Context, login string, password []byte)) *AdminRepo_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *AdminRepo_UpdatePassword_Call) Return(_a0 error) *AdminRepo_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminRepo_UpdatePassword_Call) RunAndReturn(run func(context.Context, string, []byte) error) *AdminRepo_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdminRepo creates a new instance of AdminRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepo {
	mock := &AdminRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
