// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SergeyBogomolovv/fitflow/internal/domain"
	mock "github.com/stretchr/testify/mock"

	post "github.com/SergeyBogomolovv/fitflow/internal/repo/post"
)

// PostRepo is an autogenerated mock type for the PostRepo type
type PostRepo struct {
	mock.Mock
}

type PostRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PostRepo) EXPECT() *PostRepo_Expecter {
	return &PostRepo_Expecter{mock: &_m.Mock}
}

// SavePost provides a mock function with given fields: ctx, in
func (_m *PostRepo) SavePost(ctx context.Context, in post.SavePostInput) (domain.Post, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SavePost")
	}

	var r0 domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, post.SavePostInput) (domain.Post, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, post.SavePostInput) domain.Post); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, post.SavePostInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRepo_SavePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePost'
type PostRepo_SavePost_Call struct {
	*mock.Call
}

// SavePost is a helper method to define mock.On call
//   - ctx context.Context
//   - in post.SavePostInput
func (_e *PostRepo_Expecter) SavePost(ctx interface{}, in interface{}) *PostRepo_SavePost_Call {
	return &PostRepo_SavePost_Call{Call: _e.mock.On("SavePost", ctx, in)}
}

func (_c *PostRepo_SavePost_Call) Run(run func(ctx context.Context, in post.SavePostInput)) *PostRepo_SavePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(post.SavePostInput))
	})
	return _c
}

func (_c *PostRepo_SavePost_Call) Return(_a0 domain.Post, _a1 error) *PostRepo_SavePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostRepo_SavePost_Call) RunAndReturn(run func(context.Context, post.SavePostInput) (domain.Post, error)) *PostRepo_SavePost_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostRepo creates a new instance of PostRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostRepo {
	mock := &PostRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
