// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// S3Client is an autogenerated mock type for the S3Client type
type S3Client struct {
	mock.Mock
}

type S3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *S3Client) EXPECT() *S3Client_Expecter {
	return &S3Client_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *S3Client) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// S3Client_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type S3Client_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *S3Client_Expecter) Delete(ctx interface{}, key interface{}) *S3Client_Delete_Call {
	return &S3Client_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *S3Client_Delete_Call) Run(run func(ctx context.Context, key string)) *S3Client_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *S3Client_Delete_Call) Return(_a0 error) *S3Client_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *S3Client_Delete_Call) RunAndReturn(run func(context.Context, string) error) *S3Client_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, body
func (_m *S3Client) Upload(ctx context.Context, key string, body io.Reader) (string, error) {
	ret := _m.Called(ctx, key, body)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) (string, error)); ok {
		return rf(ctx, key, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) string); ok {
		r0 = rf(ctx, key, body)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = rf(ctx, key, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// S3Client_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type S3Client_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - body io.Reader
func (_e *S3Client_Expecter) Upload(ctx interface{}, key interface{}, body interface{}) *S3Client_Upload_Call {
	return &S3Client_Upload_Call{Call: _e.mock.On("Upload", ctx, key, body)}
}

func (_c *S3Client_Upload_Call) Run(run func(ctx context.Context, key string, body io.Reader)) *S3Client_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *S3Client_Upload_Call) Return(_a0 string, _a1 error) *S3Client_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *S3Client_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader) (string, error)) *S3Client_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewS3Client creates a new instance of S3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Client {
	mock := &S3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
