http:
  port: 8080
  host: 'localhost'
  allowed_origins:
    - 'http://localhost:3000'

jwt:
  ttl: 24h

logger:
  level: debug

telegram:
  level_spec: '@every 5s'
  broadcast_spec: '@every 5s'

ai:
  model: 'gemini-2.0-flash'
  default_prompt: 'Ты — профессиональный эксперт по фитнесу, тренировкам и здоровому питанию. Твоя задача — создавать качественный, информативный и мотивирующий пост для telegram Твои посты для telegram должны быть: Основаны на научных данных и практическом опыте. Без воды, только полезная информация. Написаны доступным языком, но с профессиональной подачей. Иметь красивую подачу, используй выделение ключевых слов, эмодзи по необходимости. Я буду присылать темы для постов, а ты отвечай контентом'

s3:
  region: 'ru-central1'
  bucket: 'fitflow'
  endpoint: 'https://storage.yandexcloud.net'
